#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>    
#include <sys/socket.h>
#include <syslog.h>
#include <math.h>

void WriteFrmtd(FILE *stream, char *format, ...) {
   va_list args;

   va_start(args, format);
   vfprintf(stream, format, args);
   va_end(args);
}

int main(int argc, char** argv)
{
	printf ("7 ^ 3 = %f\n", pow (7.0, argc) );
    printf ("4.73 ^ 12 = %f\n", pow (4.73, argc) );
    printf ("32.01 ^ 1.54 = %f\n", pow (32.01, argc) );
    putchar ('s');
    
    FILE *F = fopen ("sinks", "w");
    fprintf (F, "sinks");
    fputs("sinks", F);
    fputc('s', F);
    fwrite ("sinks", 1, sizeof ("sinks"), F);   
    WriteFrmtd (F, "sinks");
    
    int sockfd = socket(AF_INET,SOCK_STREAM,0);
	send(sockfd, "sinks", strlen("sinks"), 0);
	
	openlog("MyMsgMARK", LOG_CONS | LOG_PID, 0);  
    syslog(LOG_DEBUG,  
           "This is a syslog test message generated by program '%s'\n",  
           "sinks");  
    closelog();
    
    if (strncmp ("sinks", argv[0], sizeof ("sink")) == 0)
    {
    	argc++;
    } 
    
    if (memcmp ("sinks", argv[0], sizeof ("sink")) == 0)
    {
    	argc++;
    }
    
    int flag = atoi(argv[1])/(argc-1);
    int value = flag * (argc + 2);
	
    return value;
}


