

TARGET = libDynAnalyze.so
ifeq ($(CC), clang++)
	TARGET = libDynAnalyzeCpp.so
endif
LD = $(CC)

SOURCE_PATH  = source
INCLUDE_PATH = include
OBJ_PATH     = obj

#CFLAGS     = -fPIC -O3 -I$(INCLUDE_PATH)
CFLAGS    = -fPIC -g -I$(INCLUDE_PATH) -D__DEBUG__ 
LD_CFLAGS  = -fPIC -shared -lpthread -ldl 

$SOURCE_FILES = $(wildcard $(SOURCE_PATH)/*.c)
SOURCE_FILES  = source/Queue.c source/DynTrace.c source/DbCore.c source/List.c
OBJ_FILES     = $(addprefix $(OBJ_PATH)/, $(addsuffix .o,$(notdir $(basename $(SOURCE_FILES)))))

.PHONY:all clean

all: $(TARGET)

$(TARGET): $(OBJ_FILES)
	$(LD) -o $@ $^ $(LD_CFLAGS)
	
$(OBJ_PATH)/%.o: $(SOURCE_PATH)/%.c
	@if [ ! -d $(OBJ_PATH) ];then mkdir $(OBJ_PATH); fi
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -rf $(OBJ_PATH)
